# Generated by Django 3.2.3 on 2021-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sisztrn',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, unique=True)),
                ('hincd', models.CharField(db_column='HINCD', max_length=20)),
                ('hinnm', models.CharField(db_column='HINNM', max_length=50)),
                ('baitnk', models.IntegerField(db_column='BAITNK')),
                ('gozen', models.IntegerField(db_column='GOZEN')),
                ('hradd', models.IntegerField(db_column='HRADD')),
                ('ggadd', models.IntegerField(db_column='GGADD')),
                ('tsadd', models.IntegerField(db_column='TSADD')),
                ('sizdate', models.IntegerField(db_column='SIZDATE')),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'SISZTRN',
                'managed': False,
            },
        ),
    ]
