# Generated by Django 3.2.3 on 2021-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sziapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hincatmst',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('sskcd', models.CharField(db_column='SSKCD', max_length=10)),
                ('catcd', models.CharField(db_column='CATCD', max_length=10)),
                ('catname', models.CharField(db_column='CATNAME', max_length=50)),
                ('pcatcd', models.IntegerField(blank=True, db_column='PCATCD', null=True)),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'HINCATMST',
                'managed': False,
            },
        ),
    ]
