# Generated by Django 3.2.3 on 2021-06-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sziapp', '0002_hincatmst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ckmmst',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('sskcd', models.CharField(db_column='SSKCD', max_length=10)),
                ('ckmcd', models.CharField(db_column='CKMCD', max_length=10)),
                ('ckmname', models.CharField(db_column='CKMNAME', max_length=50)),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'CKMMST',
                'managed': False,
            },
        ),
    ]
