# Generated by Django 3.2.3 on 2021-09-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sziapp', '0004_ktnmst_sskmst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hikmeilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_cd', models.IntegerField(db_column='STORE_CD')),
                ('jancd', models.CharField(db_column='JANCD', max_length=20)),
                ('hikdt', models.DateField(db_column='HIKDT')),
                ('hiksu', models.BigIntegerField(db_column='HIKSU')),
                ('hikgaku', models.BigIntegerField(db_column='HIKGAKU')),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'HIKMEILOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hinmst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jancd', models.CharField(db_column='JANCD', max_length=13)),
                ('hinnm', models.CharField(db_column='HINNM', max_length=100)),
                ('ckmcd', models.IntegerField(db_column='CKMCD')),
                ('bmncd', models.IntegerField(blank=True, db_column='BMNCD', null=True)),
                ('linecd', models.IntegerField(blank=True, db_column='LINECD', null=True)),
                ('classcd', models.IntegerField(blank=True, db_column='CLASSCD', null=True)),
                ('catcd', models.CharField(blank=True, db_column='CATCD', max_length=10, null=True)),
                ('syokbn', models.CharField(blank=True, db_column='SYOKBN', max_length=100, null=True)),
                ('tankakng', models.BigIntegerField(blank=True, db_column='TANKAKNG', null=True)),
                ('baitnk', models.BigIntegerField(blank=True, db_column='BAITNK', null=True)),
                ('gentnk', models.DecimalField(blank=True, db_column='GENTNK', decimal_places=0, max_digits=6, null=True)),
                ('yobi1', models.CharField(blank=True, db_column='YOBI1', max_length=20, null=True)),
                ('yobi2', models.CharField(blank=True, db_column='YOBI2', max_length=20, null=True)),
                ('yobi3', models.CharField(blank=True, db_column='YOBI3', max_length=20, null=True)),
                ('yobi4', models.CharField(blank=True, db_column='YOBI4', max_length=20, null=True)),
                ('yobi5', models.CharField(blank=True, db_column='YOBI5', max_length=20, null=True)),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'HINMST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timesalesmeilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_date', models.DateField(db_column='DEAL_DATE')),
                ('yobi', models.IntegerField(db_column='YOBI')),
                ('store_cd', models.IntegerField(db_column='STORE_CD')),
                ('jancd', models.CharField(db_column='JANCD', max_length=13)),
                ('jancd_2', models.CharField(db_column='JANCD_2', max_length=13)),
                ('hinnm', models.CharField(db_column='HINNM', max_length=50)),
                ('seltmzncd', models.IntegerField(db_column='SELTMZNCD')),
                ('classcd', models.IntegerField(db_column='CLASSCD')),
                ('bmncd', models.IntegerField(db_column='BMNCD')),
                ('gentnk', models.BigIntegerField(blank=True, db_column='GENTNK', null=True)),
                ('sales_itm', models.BigIntegerField(blank=True, db_column='SALES_ITM', null=True)),
                ('sales_amt', models.BigIntegerField(blank=True, db_column='SALES_AMT', null=True)),
                ('item_dis_amt', models.BigIntegerField(blank=True, db_column='ITEM_DIS_AMT', null=True)),
                ('nebikiritu0', models.IntegerField(blank=True, db_column='NebikiRitu0', null=True)),
                ('nebikiritu10', models.IntegerField(blank=True, db_column='NebikiRitu10', null=True)),
                ('nebikiritu20', models.IntegerField(blank=True, db_column='NebikiRitu20', null=True)),
                ('nebikiritu30', models.IntegerField(blank=True, db_column='NebikiRitu30', null=True)),
                ('nebikiritu40', models.IntegerField(blank=True, db_column='NebikiRitu40', null=True)),
                ('nebikiritu50', models.IntegerField(blank=True, db_column='NebikiRitu50', null=True)),
                ('nebikiritu99', models.IntegerField(blank=True, db_column='NebikiRitu99', null=True)),
                ('lastseltmzncd', models.IntegerField(db_column='LASTSELTMZNCD')),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'TIMESALESMEILOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField()),
            ],
        ),
    ]
