# Generated by Django 3.2.3 on 2022-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sziapp', '0006_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplan',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sskcd', models.CharField(db_column='SSKCD', max_length=10)),
                ('ktncd', models.CharField(db_column='KTNCD', max_length=10)),
                ('ckmcd', models.CharField(db_column='CKMCD', max_length=10)),
                ('catcd', models.CharField(db_column='CATCD', max_length=10)),
                ('hincd', models.CharField(db_column='HINCD', max_length=20)),
                ('hinnm', models.CharField(db_column='HINNM', max_length=50)),
                ('callcd', models.IntegerField(db_column='CALLCD')),
                ('size', models.CharField(db_column='SIZE', max_length=10)),
                ('tray', models.CharField(db_column='TRAY', max_length=20)),
                ('baitnk', models.IntegerField(db_column='BAITNK')),
                ('gozen', models.IntegerField(db_column='GOZEN')),
                ('hradd', models.IntegerField(db_column='HRADD')),
                ('ggadd', models.IntegerField(db_column='GGADD')),
                ('tsadd', models.IntegerField(db_column='TSADD')),
                ('yobi1', models.CharField(blank=True, db_column='YOBI1', max_length=50, null=True)),
                ('yobi2', models.CharField(blank=True, db_column='YOBI2', max_length=50, null=True)),
                ('yobi3', models.CharField(blank=True, db_column='YOBI3', max_length=50, null=True)),
                ('yobi4', models.CharField(blank=True, db_column='YOBI4', max_length=50, null=True)),
                ('yobi5', models.CharField(blank=True, db_column='YOBI5', max_length=50, null=True)),
                ('sizdate', models.IntegerField(db_column='SIZDATE')),
                ('makdt', models.DateTimeField(db_column='MAKDT')),
                ('updt', models.DateTimeField(db_column='UPDT')),
            ],
            options={
                'db_table': 'WORKPLAN',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Sisztrn',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
